public enum StateEnum
{
    //EnemyStates
    EnemyPatrol,
    EnemyAlert,
    Attack,
    EnemyEscape,
    EnemySeek,
    EnemyLookingState,
    //MouseStates
    MousePatrolState,
    MouseLookingState,
    MouseEscapeState,
    //PlayerStates
    PlayerInvisible,
    PlayerIdle,
    PlayerWalk,
    PlayerRun
}