public enum StateEnum
{
    //RedMouseStates
    EnemyPatrol,
    EnemyAlert,
    Attack,
    EnemyEscape,
    EnemySeek,
    EnemyLookingState,
    //GreenMouseStates
    MousePatrolState,
    MouseLookingState,
    MouseEscapeState,
    //BlueMouseStates
    FlockingPatrolState,
    FlockingAttackState,
    BlueEscapeState,
    //PlayerStates
    PlayerInvisible,
    PlayerIdle,
    PlayerWalk,
    PlayerRun
}